B get discogs vinyls list by username
Vinyl-team/Vinyl pull request #14
Opened 2021-04-15 17:38 UTC by AlexKievDeveloper

2021-04-15 18:40 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/Starter.java
> -import static java.lang.Integer.parseInt;
You still use parseInt, but I can't see the import

2021-04-15 18:40 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsService.java
> +    private final ObjectMapper objectMapper;
Reminder that we agreed on an empty row after classes' '{' and before closing '}'.

2021-04-15 18:40 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsService.java
> +            throw new RuntimeException("Exception while want list json processing", e);
Format is {'wantList':{}}

2021-04-15 18:40 UTC, Greengrer commented on src/test/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsServiceITest.java
> +        //prepare
Maybe just getVinylsByReleasesTest()?

2021-04-15 20:10 UTC, TarasOrlovskyi submitted a review, later dismissed

2021-04-16 06:59 UTC, Greengrer requested changes

2021-04-16 06:59 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsService.java
> +            logger.error("{'WantList':{}}", discogsWantList);
Add error to logger to have stacktrace

2021-04-16 06:59 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsService.java
> +        return vinylsReleasesList;
Add logger.debug("Resulting vinyls releases list is {'releasesList':{}}", vinylsReleasesList);
before return.

2021-04-16 06:59 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/PropertiesReader.java
> +                .getResourceAsStream("application.properties")) {
If you don't use indpendentPropertiesFile, delete it.(row 16).

2021-04-16 06:59 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/PropertiesReader.java
>                      inputStream, independentPropertiesFile);
Decide if you use independentPropertiesFile string or just use "application.properties" everywhere

2021-04-16 06:59 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/PropertiesReader.java
> +                    .getResourceAsStream("dev.application.properties")) {
I think you are using the version that accidentally changed PropertiesReader to how it was before logger.

Do you use String env?

2021-04-16 06:59 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/PropertiesReader.java
> -
Why delete debug that tells that input stream is valid?

Add empty row before end of class.

2021-04-16 07:56 UTC, TarasOrlovskyi submitted a review, later dismissed

2021-04-16 08:47 UTC, Greengrer requested changes

2021-04-16 08:47 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsService.java
> +                    " {'callback url': {}} ", CONSUMER_KEY, CONSUMER_SECRET, USER_AGENT, CALLBACK_URL, e);
{'consumerKey': {}, 'consumerSecret': {}, 'userAgent': {}, 'callbackUrl': {}}
Sorry I was unclear.

2021-04-16 08:47 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultDiscogsService.java
> +            throw new RuntimeException("Exception while want list json processing", e);
Starting with lowercase, like variable. "{'wantList':{}}"

2021-04-16 08:48 UTC, TarasOrlovskyi submitted a review, later dismissed

2021-04-16 09:02 UTC, Greengrer approved these changes

2021-04-16 09:03 UTC, TarasOrlovskyi approved these changes

2021-04-16 09:04 UTC, merged