Security
Vinyl-team/Vinyl pull request #32
Opened 2021-04-30 17:45 UTC by TarasOrlovskyi

2021-04-30 17:49 UTC, AlexKievDeveloper submitted a review, later dismissed

2021-04-30 18:01 UTC, Greengrer requested changes
I might be wrong about the "exist session" part.

2021-04-30 18:01 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/web/servlets/SignUpServlet.java
> +                attributes.put("message", "Sorry, but a user with this email address already exists!");
"user already exists" shouldn't be displayed: it's a security issue.
Just "Sorry, couldn't sign you in. Check email and password?" or something.

2021-04-30 18:01 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/web/servlets/SignUpServlet.java
> +            attributes.put("message", "Sorry, the passwords do not match!");
This shouldn't be checked inside servlet, allowing submit only when passwords match is a task for front.
Here you'll find a couple answers without javascript: https://stackoverflow.com/questions/9142527/can-you-require-two-form-fields-to-match-with-html5

2021-04-30 18:01 UTC, Greengrer commented on src/test/java/com/vinylteam/vinyl/web/servlets/SignOutServletTest.java
> +    @DisplayName("Checks if all right methods are called & exist session was delete")
*deleteD.

2021-04-30 18:01 UTC, Greengrer commented on src/test/java/com/vinylteam/vinyl/web/servlets/SignOutServletTest.java
> +    void doGetWithExistSessionTest() throws IOException {
ExistingSession

2021-04-30 18:01 UTC, Greengrer commented on src/test/java/com/vinylteam/vinyl/web/servlets/SignOutServletTest.java
> +    @DisplayName("Checks if all right methods are called & exist session was delete")
existing session: існуюча сесія була видалена.

2021-04-30 18:01 UTC, Greengrer commented on src/test/java/com/vinylteam/vinyl/web/servlets/SignOutServletTest.java
> +    void doGetWithNonExistSessionTest() throws IOException {
NotExisting
or
NonExistent.

2021-05-03 09:18 UTC, Greengrer requested changes
That was cool!

2021-05-03 09:18 UTC, Greengrer commented on src/main/resources/templates/registration.html
> +                            <span class="tooltiptext">LogOut</span>
*Log out is better than LogOut

2021-05-03 09:18 UTC, Greengrer commented on src/main/resources/templates/registration.html
> +                                           placeholder="Discogs User Name">
Add explanation what Discogs username is for, maybe?

2021-05-03 09:18 UTC, Greengrer commented on src/main/resources/templates/registration.html
> +                                           placeholder="Discogs User Name">
"When referring to an identity used with a password, "username" is used. If you are referring to a real name or full name, "user name" could be used. As far as "user-name," it is rarely used. In our earlier example, "John Smith" is the user name, and "smitj" is the username used with his password." (https://www.computerhope.com/jargon/u/username.htm)

Username, not User Name

2021-05-03 09:18 UTC, Greengrer commented on src/test/java/com/vinylteam/vinyl/web/servlets/SignOutServletTest.java
> +        inOrderResponse.verify(mockedResponse).sendRedirect("/");
Reusing same mock with inOrder is not secure.
(1)mockedResponse.setStatus(...);
(2)mockedResponse.sendRedirect(...);
(3)inOrderResponse.verify(...).setStatus(...);
(4)inOrderResponse.verify(...).sendRedirect(...);
(5)mockedResponse.setStatus(...);
(6)mockedResponse.sendRedirect(...);
(7)inOrderResponse.verify(...).setStatus(...);
(8)inOrderResponse.verify(...).sendRedirect(...);

The same as:

(1)mockedResponse.setStatus(...);
(2)mockedResponse.sendRedirect(...);
(5)mockedResponse.setStatus(...);
(6)mockedResponse.sendRedirect(...);
(3)inOrderResponse.verify(...).setStatus(...);
(4)inOrderResponse.verify(...).sendRedirect(...);
(7)inOrderResponse.verify(...).setStatus(...);
(8)inOrderResponse.verify(...).sendRedirect(...);

It has a potential to jumble tests up. Better to have @BeforeEach that nulls them and reassigns new mocks.

2021-05-03 09:23 UTC, AlexKievDeveloper approved these changes, later dismissed

2021-05-03 09:23 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/web/servlets/SignUpServlet.java
> +            attributes.put("message", "Sorry, but the email couldn't be registered. Check email and password!");
Я бы поменял email на user:
Sorry, but the user couldn't be registered.

2021-05-03 10:33 UTC, Greengrer approved these changes

2021-05-03 10:54 UTC, AlexKievDeveloper approved these changes

2021-05-03 10:55 UTC, merged