Add JunoVinylService:
Vinyl-team/Vinyl pull request #35
Opened 2021-05-10 06:44 UTC by TEdwardJ

- Add a new vinyl service implementation for juno.co.uk, add it to shops parser;
 - Add Juno to the shops list;

2021-05-10 06:51 UTC, Greengrer requested changes
Okay, that is pretty cool.

2021-05-10 06:51 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +        log.debug("Resulting list of RawOffers from RawOffer.ua is {'RawOffersRawOfferUaList':{}}", RawOffersJunoRawOfferList);
Resulting list of rawOffers from juno.co.uk is {'rawOffers':{}}

2021-05-10 06:51 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +        List<RawOffer> RawOffersJunoRawOfferList = new ArrayList<>(RawOffers);
junoRawOffers/rawOffersList/junoRawOffersList

2021-05-10 06:51 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +        return RawOffersJunoRawOfferList;
junoRawOffers/rawOffersList/junoRawOffersList

2021-05-10 06:51 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +            var genre = infoDetails.get(4).text();
@AlexKievDeveloper should we use String, or is var sufficient?

2021-05-10 08:21 UTC, AlexKievDeveloper requested changes

2021-05-10 08:21 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +    Pattern pageNumberPattern = Pattern.compile("/([0-9]+)/");
Can we add private access modifier?

2021-05-10 08:21 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +
Please remove empty row

2021-05-10 08:21 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +            return null;
We shouldn`t return null. Let`s use optional

2021-05-10 08:21 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +            return null;
We shouldn`t return null. Better optional

2021-05-10 08:21 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +            log.error("Error during RawOffer creation from the HTML element {}", item, e);
Don`t we need test on this method and other private methods?

2021-05-10 08:26 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +        log.debug("Resulting list of RawOffers from RawOffer.ua is {'RawOffersRawOfferUaList':{}}", RawOffersJunoRawOfferList);
> Resulting list of rawOffers from juno.co.uk is {'rawOffers':{}}

molodec! vnimatelnaya! (c) Tolik

2021-05-10 08:40 UTC, AlexKievDeveloper requested changes

2021-05-10 08:40 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +    private final String RawOfferInfoItemsSelector = "div.vi-text";
1) All variables names from starts from lower case
2) We will have one instance of the class. We can make all variables static constants.

2021-05-10 08:40 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +        List<RawOffer> RawOffersJunoRawOfferList = new ArrayList<>(RawOffers);
Variable names starts from lower case

2021-05-10 08:40 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +            return null;
We should discuss why you need to return null

2021-05-10 08:42 UTC, AlexKievDeveloper requested changes

2021-05-10 08:42 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/impl/JunoVinylParser.java
> +        pages = getFullPageLinksList(pages);
We shouldn`t reuse variables

2021-05-11 06:42 UTC, Greengrer submitted a review, later dismissed

2021-05-11 10:24 UTC, Greengrer approved these changes, later dismissed

2021-05-11 10:29 UTC, AlexKievDeveloper commented on src/test/java/com/vinylteam/vinyl/util/impl/JunoVinylParserTest.java
> +    public void givenHtmlImgElement_whenRawOfferISCreated_thenCorrect() throws IOException {
Why in  the test names you use CamelCase with under lines? Please use only CamelCase. 
Please add @DisplayName annotation on the top of each test to describe what exactly test doing

2021-05-11 10:34 UTC, TEdwardJ commented on src/test/java/com/vinylteam/vinyl/util/impl/JunoVinylParserTest.java
> +    public void givenHtmlImgElement_whenRawOfferISCreated_thenCorrect() throws IOException {
just in order to follow some naming strategy for tests methods: https://dzone.com/articles/7-popular-unit-test-naming

@DisplayName - got it, will apply

2021-05-11 10:58 UTC, AlexKievDeveloper approved these changes

2021-05-11 11:00 UTC, Greengrer approved these changes

2021-05-11 11:12 UTC, merged