Contact us add changes
Vinyl-team/Vinyl pull request #51
Opened 2021-05-20 19:21 UTC by littlepony99

2021-05-20 19:35 UTC, AlexKievDeveloper requested changes

2021-05-20 19:35 UTC, AlexKievDeveloper commented on pom.xml
> +<!--        </dependency>-->
Please remove commented code

2021-05-20 19:35 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/service/CaptchaService.java
> +    boolean validateCaptcha(String captchaId, String response);
Please add empty row after interface/class declaration and before closing. It is our code style

2021-05-20 19:35 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCaptchaService.java
> +    }
Please add empty row before closing class

2021-05-20 19:35 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/CaptchaValidator.java
> +    }
Please add empty row after interface/class declaration and before closing. It is our code style

2021-05-20 19:35 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/web/servlets/ImageCaptchaServlet.java
> +    DefaultCaptchaService captchaService = new DefaultCaptchaService();
Please add private access modifier

2021-05-20 19:35 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/web/servlets/ImageCaptchaServlet.java
> +    }
Please add empty row after interface/class declaration and before closing. It is our code style

2021-05-20 20:10 UTC, TEdwardJ submitted a review, later dismissed

2021-05-20 20:10 UTC, TEdwardJ commented on src/test/java/com/vinylteam/vinyl/dao/jdbc/mapper/UserPostRowMapperTest.java
> +        LocalDateTime createdAt = LocalDateTime.of(2021, 5, 19, 21, 0);
is there sense to use  now() method too?
Just in order to execute tests on the more wide variety of input data?

2021-05-20 20:45 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/util/CaptchaValidator.java
>      private static ImageCaptchaService instance = new DefaultManageableImageCaptchaService();
Maybe should rename variable to plain: "imageCaptchaService" ?

2021-05-20 20:52 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCaptchaService.java
> +            log.error("Error during captcha generation!");
Lets add exception to logger: log.error("Error during captcha generation!", e);

2021-05-20 20:52 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCaptchaService.java
> +            e.printStackTrace();
Maybe we should throw new RuntimeException for stop request processing?

2021-05-20 20:52 UTC, AlexKievDeveloper commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCaptchaService.java
> +        return null;
Please don`t return null. Use Optional for avoid NullPointerException

2021-05-21 12:18 UTC, AlexKievDeveloper approved these changes

2021-05-21 12:19 UTC, AlexKievDeveloper approved these changes

2021-05-21 12:39 UTC, TEdwardJ approved these changes

2021-05-21 12:49 UTC, merged